version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: familywallet-postgres
    environment:
      POSTGRES_DB: familywallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - familywallet-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: familywallet-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - familywallet-network

  # MailHog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: familywallet-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - familywallet-network

  # Backend API (Kotlin + Spring Boot)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: familywallet-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/familywallet_dev
      SPRING_DATASOURCE_USERNAME: familywallet_dev
      SPRING_DATASOURCE_PASSWORD: familywallet_dev
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - ./backend:/app
      - /app/build
      - /app/.gradle
    networks:
      - familywallet-network
    command: ./gradlew bootRun

volumes:
  postgres_data:
  redis_data:

networks:
  familywallet-network:
    driver: bridge
