spring:
  application:
    name: familywallet-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/familywallet
    username: familywallet
    password: familywallet
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  redis:
    host: localhost
    port: 6379
    password: 
    timeout: 2000ms
  
  security:
    jwt:
      secret: familywallet-secret-key-for-development-only
      expiration: 86400000 # 24 hours
  
  mail:
    host: localhost
    port: 1025
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8080

logging:
  level:
    com.familywallet: DEBUG
    org.springframework.security: DEBUG
